name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (ajuste a versão conforme necessário)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Instala as dependências
      - name: Install dependencies
        run: npm install

      # Step 4: Build a aplicação com Vite
      - name: Build application
        run: npm run build

      # Step 5: Start server for Cypress tests
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
